name: Run Cypress Tests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/checkout@v6
        with:
          node-version: "18.18.2"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run e2e
